name: Deploy Terraform GCP

# 1. Quando essa pipeline vai rodar?
on:
  push:
    branches:
      - dev   
      - main 
    paths:
      - 'terraform/**' 
# 2. O que ela vai fazer?
jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_repo_name: "youtube-etl-gcp" 
      TF_VAR_branch: ${{ github.ref_name }}

    steps:
      - name: 📥 Clonar o Repositório
        uses: actions/checkout@v3

      - name: 🛠️ Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: 🔐 Autenticar no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: 🚀 Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: 🔍 Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: ✅ Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform